// Package spec defines the OAR Runtime Specification API types.
// These types model config.json (the agent bundle configuration) and mirror
// the schema defined in docs/design/runtime/config-spec.md.
// No I/O or business logic belongs here.
package spec

import "github.com/open-agent-d/open-agent-d/api"

// Config is the top-level OAR Runtime Specification config.json structure.
// Generated by agentd, consumed by agent-shim.
type Config struct {
	// OarVersion is the version of the OAR Runtime Specification (SemVer).
	// Consumers MUST reject unknown major versions.
	OarVersion string `json:"oarVersion"`

	// Metadata describes the identity of this agent instance.
	Metadata Metadata `json:"metadata"`

	// AgentRoot specifies the agent's root working directory within the bundle.
	// Analogous to OCI config.json's "root" field — the path is relative to the
	// bundle directory and resolved to an absolute path by agent-shim at create time.
	// agentd (specifically the Workspace Manager) is responsible for creating this
	// directory and linking it into the bundle before handing the bundle to agent-shim.
	AgentRoot AgentRoot `json:"agentRoot"`

	// AcpAgent describes the ACP agent's complete runtime configuration.
	AcpAgent AcpAgent `json:"acpAgent"`

	// Permissions specifies the policy for handling agent-initiated fs/* and
	// terminal/* requests. Defaults to ApproveAll.
	Permissions PermissionPolicy `json:"permissions,omitempty"`
}

// AgentRoot specifies the agent's root working directory within the bundle.
// Mirrors OCI's "root" object (which has "path" and "readonly" fields).
type AgentRoot struct {
	// Path is the path to the agent root directory, relative to the bundle directory.
	// Typically "workspace", which agentd symlinks to the actual workspace path.
	// REQUIRED. Must not be empty.
	Path string `json:"path"`
}

// Metadata describes the identity of an agent instance.
type Metadata struct {
	// Name is the instance name (e.g. "auth-refactor-agent").
	// This is an instance name, not an agent type name.
	Name string `json:"name"`

	// Annotations contains arbitrary key-value metadata.
	// Keys SHOULD use reverse-domain notation (e.g. "org.openagents.task").
	Annotations map[string]string `json:"annotations,omitempty"`
}

// AcpAgent describes the ACP agent's complete runtime configuration.
// The field name explicitly includes "acp" — this spec only supports ACP agents.
type AcpAgent struct {
	// SystemPrompt is the agent's role definition and capability constraints.
	// Passed to ACP session/new as the systemPrompt parameter.
	SystemPrompt string `json:"systemPrompt,omitempty"`

	// Process specifies how to start the ACP agent process (fork/exec params).
	Process AcpProcess `json:"process"`

	// Session specifies ACP session/new parameters (mcpServers).
	Session AcpSession `json:"session,omitempty"`
}

// AcpProcess specifies how to launch the ACP agent process.
type AcpProcess struct {
	// Command is the ACP agent executable (analogous to OCI process.args[0]).
	Command string `json:"command"`

	// Args are the command-line arguments passed to Command.
	Args []string `json:"args,omitempty"`

	// Env is the list of process environment variable overrides in KEY=VALUE format.
	// agentd merges runtimeClass env + orchestrator request env before writing this.
	// At runtime, agent-shim merges the parent process environment as the base and
	// applies these entries on top, so agents always inherit a complete system
	// environment (PATH, HOME, etc.) while config-specified variables take precedence.
	Env []string `json:"env,omitempty"`
}

// AcpSession specifies ACP session/new parameters.
// Fields align with the ACP protocol's NewSessionRequest.
type AcpSession struct {
	// McpServers is the list of MCP services available to the agent.
	// Corresponds to ACP session/new mcpServers parameter.
	McpServers []McpServer `json:"mcpServers,omitempty"`
}

// McpServer is a single MCP service endpoint.
type McpServer struct {
	// Type is the transport type. Valid values: "http", "sse", "stdio".
	Type string `json:"type"`

	// Name is the human-readable name identifying this MCP server.
	// Used for stdio transport; optional for http/sse.
	Name string `json:"name,omitempty"`

	// URL is the MCP service URL. Used for http/sse transports.
	URL string `json:"url,omitempty"`

	// Command is the MCP server executable path. Used for stdio transport.
	Command string `json:"command,omitempty"`

	// Args are the command-line arguments for the stdio MCP server.
	// Not omitempty — ACP agents require an explicit empty array, not null/absent.
	Args []string `json:"args"`

	// Env is the environment variables for the stdio MCP server.
	// Not omitempty — ACP agents require an explicit empty array, not null/absent.
	Env []api.EnvVar `json:"env"`
}

// PermissionPolicy controls how agent-shim handles agent-initiated fs/* and
// terminal/* requests. The policy is set at session creation and is immutable.
type PermissionPolicy string

const (
	// ApproveAll automatically approves all fs/* and terminal/* operations.
	ApproveAll PermissionPolicy = "approve_all"

	// ApproveReads automatically approves read operations; write operations
	// return a deny error.
	ApproveReads PermissionPolicy = "approve_reads"

	// DenyAll returns a deny error for all fs/* and terminal/* operations.
	DenyAll PermissionPolicy = "deny_all"
)

// IsValid reports whether p is a known PermissionPolicy value.
func (p PermissionPolicy) IsValid() bool {
	switch p {
	case ApproveAll, ApproveReads, DenyAll:
		return true
	}
	return false
}

// String implements fmt.Stringer.
func (p PermissionPolicy) String() string {
	return string(p)
}
