// Package api defines the MASS Runtime Specification types:
// config.json (bundle configuration) and state.json (runtime state).
// These types mirror the schema defined in docs/design/runtime/config-spec.md
// and docs/design/runtime/runtime-spec.md. No I/O or business logic belongs here.
package api

// Config is the top-level MASS Runtime Specification config.json structure.
// Generated by mass, consumed by agent-run.
type Config struct {
	// MassVersion is the version of the MASS Runtime Specification (SemVer).
	// Consumers MUST reject unknown major versions.
	MassVersion string `json:"massVersion"`

	// Metadata describes the identity of this agent instance.
	Metadata Metadata `json:"metadata"`

	// AgentRoot specifies the agent's root working directory within the bundle.
	// Analogous to OCI config.json's "root" field — the path is relative to the
	// bundle directory and resolved to an absolute path by agent-run at create time.
	// mass (specifically the Workspace Manager) is responsible for creating this
	// directory and linking it into the bundle before handing the bundle to agent-run.
	AgentRoot AgentRoot `json:"agentRoot"`

	// ClientProtocol specifies the communication protocol between agent-run
	// and the agent process. Determines how bootstrap, prompt, and event
	// streaming are handled.
	ClientProtocol ClientProtocol `json:"clientProtocol"`

	// Process specifies how to launch the agent process (fork/exec params).
	// Shared across all client protocols.
	Process Process `json:"process"`

	// Session specifies session-level configuration: system prompt,
	// permissions, and MCP servers. Delivery method depends on ClientProtocol.
	Session Session `json:"session,omitempty"`
}

// AgentRoot specifies the agent's root working directory within the bundle.
// Mirrors OCI's "root" object (which has "path" and "readonly" fields).
type AgentRoot struct {
	// Path is the path to the agent root directory, relative to the bundle directory.
	// Typically "workspace", which mass symlinks to the actual workspace path.
	// REQUIRED. Must not be empty.
	Path string `json:"path"`
}

// Metadata describes the identity of an agent instance.
type Metadata struct {
	// Name is the instance name (e.g. "auth-refactor-agent").
	// This is an instance name, not an agent type name.
	Name string `json:"name"`

	// Annotations contains arbitrary key-value metadata.
	// Keys SHOULD use reverse-domain notation (e.g. "org.openagents.task").
	Annotations map[string]string `json:"annotations,omitempty"`
}

// ClientProtocol specifies the communication protocol between agent-run
// and the agent process.
type ClientProtocol string

const (
	// ClientProtocolACP communicates via ACP protocol over stdio.
	ClientProtocolACP ClientProtocol = "acp"
)

// IsValid reports whether p is a known ClientProtocol value.
func (p ClientProtocol) IsValid() bool {
	switch p {
	case ClientProtocolACP:
		return true
	}
	return false
}

// Process specifies how to launch an agent process.
// Shared across all client protocols.
type Process struct {
	// Command is the agent executable (analogous to OCI process.args[0]).
	Command string `json:"command"`

	// Args are the command-line arguments passed to Command.
	Args []string `json:"args,omitempty"`

	// Env is the list of process environment variable overrides in KEY=VALUE format.
	// mass merges runtimeClass env + orchestrator request env before writing this.
	// At runtime, agent-run merges the parent process environment as the base and
	// applies these entries on top, so agents always inherit a complete system
	// environment (PATH, HOME, etc.) while config-specified variables take precedence.
	Env []string `json:"env,omitempty"`
}

// Session specifies session-level configuration.
// Shared across all client protocols; delivery method depends on ClientProtocol.
type Session struct {
	Meta map[string]any `json:"_meta,omitempty"`

	// SystemPrompt is the agent's role definition and capability constraints.
	// How it is delivered depends on ClientProtocol:
	//   - ACP: via session/new or first prompt (ACP bootstrap)
	SystemPrompt string `json:"systemPrompt,omitempty"`

	// Permissions controls how agent-run handles agent-initiated
	// fs/* and terminal/* requests. Default: ApproveAll.
	Permissions PermissionPolicy `json:"permissions,omitempty"`

	// McpServers is the list of MCP services available to the agent.
	McpServers []McpServer `json:"mcpServers,omitempty"`
}

// McpServer is a single MCP service endpoint.
type McpServer struct {
	// Type is the transport type. Valid values: "http", "sse", "stdio".
	Type string `json:"type"`

	// Name is the human-readable name identifying this MCP server.
	// Used for stdio transport; optional for http/sse.
	Name string `json:"name,omitempty"`

	// URL is the MCP service URL. Used for http/sse transports.
	URL string `json:"url,omitempty"`

	// Command is the MCP server executable path. Used for stdio transport.
	Command string `json:"command,omitempty"`

	// Args are the command-line arguments for the stdio MCP server.
	// Not omitempty — ACP agents require an explicit empty array, not null/absent.
	Args []string `json:"args"`

	// Env is the environment variables for the stdio MCP server.
	// Not omitempty — ACP agents require an explicit empty array, not null/absent.
	Env []EnvVar `json:"env"`
}

// PermissionPolicy controls how agent-run handles agent-initiated fs/* and
// terminal/* requests. The policy is set at session creation and is immutable.
type PermissionPolicy string

const (
	// ApproveAll automatically approves all fs/* and terminal/* operations.
	ApproveAll PermissionPolicy = "approve_all"

	// ApproveReads automatically approves read operations; write operations
	// return a deny error.
	ApproveReads PermissionPolicy = "approve_reads"

	// DenyAll returns a deny error for all fs/* and terminal/* operations.
	DenyAll PermissionPolicy = "deny_all"
)

// IsValid reports whether p is a known PermissionPolicy value.
func (p PermissionPolicy) IsValid() bool {
	switch p {
	case ApproveAll, ApproveReads, DenyAll:
		return true
	}
	return false
}

// String implements fmt.Stringer.
func (p PermissionPolicy) String() string {
	return string(p)
}
